image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake c:\projects\source -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15"

    cmake --build .
